# -*- coding: utf-8 -*-
"""LR_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3VwsbHP_u7tUv60NAofdVpRgQnUEo-f
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data=pd.read_csv('/content/drive/My Drive/ML/Linear Regression/dataset/data.csv')
display(data.head())
display(data.columns)

columns=['X']
features=data[columns] #predictor
target=data['Y'] #to be predicted

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.5,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

import matplotlib.pyplot as plt
plt.scatter(X_train,y_train,color='red',label='Actual')
plt.plot(X_test,y_pred,color='blue',label='Predicted')
plt.xlim(0, 100)
plt.ylim(0, 100)
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()
plt.grid()
plt.show()

print("Intercept(c):",model.intercept_)
print("Coefficient(m):",model.coef_)